import os
import pandas as pd
import numpy as np
os. chdir('data science practice')
mixer_data = pd.read_csv('Bosch Pro 1000W.csv')
car_data = pd.read_csv('Toyota.csv', na_values=['??', '????'], index_col=0)
mixer_data1 = mixer_data.copy(deep=True)

print(mixer_data1.size)
print(mixer_data1.index)
print(mixer_data1.columns)
print(mixer_data1.shape)
print(mixer_data1.memory_usage())
print(mixer_data1.ndim)
print(mixer_data1.head(5))
print(mixer_data1.tail(3))
print(mixer_data1.at[4, 'Title'])
print(mixer_data1.iat[3, 3])
print(mixer_data1.loc[:, 'Title'])
print(mixer_data1.dtypes)
print(mixer_data1.info())
print(car_data.astype(str))
print(car_data['FuelType'].nbytes)
print(np.unique(car_data['Doors']))
car_data['Doors'].replace('three', 3, inplace=True)
car_data['Doors'].replace('four', 4, inplace=True)
car_data['Doors'].replace('five', 5, inplace=True)
print(np.unique(car_data['Doors']))
